# Generated by Django 2.2.7 on 2019-11-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pylotapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentaudio',
            name='counter',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Счетчик'),
        ),
        migrations.AlterField(
            model_name='contenttext',
            name='counter',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Счетчик'),
        ),
        migrations.AlterField(
            model_name='contentvideo',
            name='counter',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Счетчик'),
        ),
        migrations.AlterField(
            model_name='page',
            name='counter',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Счетчик'),
        ),
    ]
