# Generated by Django 2.2.7 on 2019-11-23 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pylotapp', '0002_auto_20191122_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentvideo',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contentvideos', to='pylotapp.Page', verbose_name='Страница'),
        ),
    ]
