# Generated by Django 2.2.7 on 2019-11-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pylotapp', '0003_auto_20191123_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='counter',
            field=models.PositiveIntegerField(default=0, verbose_name='Счетчик'),
        ),
    ]
