# Generated by Django 2.2.7 on 2019-11-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pylotapp', '0004_auto_20191123_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentaudio',
            name='counter',
            field=models.PositiveIntegerField(default=0, verbose_name='Счетчик'),
        ),
        migrations.AlterField(
            model_name='contenttext',
            name='counter',
            field=models.PositiveIntegerField(default=0, verbose_name='Счетчик'),
        ),
        migrations.AlterField(
            model_name='contentvideo',
            name='counter',
            field=models.PositiveIntegerField(default=0, verbose_name='Счетчик'),
        ),
    ]
